branch-defaults:
  master:
    environment: null
    group_suffix: null
global:
  application_name: woosungchu
  branch: null
  default_ec2_keyname: woosungchu
  default_platform: Python 3.4
  default_region: ap-northeast-2
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
